#pragma once

#include "Board.h"
#include "MoveGen.h"
#include "Types.h"
#include <memory>
#include <string>
#include <vector>
#include <atomic>
#include "rust/cxx.h"

// Forward declare SearchEngine to avoid circular dependencies
namespace opera {
    class SearchEngine;
    struct SearchResult;
}

namespace opera {

// Forward declarations - these structs are generated by cxx from Rust definitions
struct FFISearchLimits;
struct FFISearchResult;
struct FFISearchInfo;

// SearchEngineWrapper manages SearchEngine lifecycle for FFI
// Owns the stop flag and search engine instance
class SearchEngineWrapper {
private:
    std::unique_ptr<SearchEngine> engine;
    std::atomic<bool> stop_flag;

public:
    explicit SearchEngineWrapper(Board& board);
    ~SearchEngineWrapper();

    // Non-copyable
    SearchEngineWrapper(const SearchEngineWrapper&) = delete;
    SearchEngineWrapper& operator=(const SearchEngineWrapper&) = delete;

    // Start search (blocking call)
    FFISearchResult search(const FFISearchLimits& limits);

    // Stop search immediately
    void stop();

    // Check if currently searching
    bool is_searching() const;

    // Reset for new game
    void reset();
};

} // namespace opera

// C++ Functions for Rust FFI (cxx compatible)
// These functions will be called from Rust through the cxx bridge

// Need to include rust::Str for cxx compatibility
#include "rust/cxx.h"

// Board operations - simplified for initial FFI
std::unique_ptr<opera::Board> create_board();
bool board_set_fen(opera::Board& board, rust::Str fen);
bool board_make_move(opera::Board& board, rust::Str move_str);
rust::String board_get_fen(const opera::Board& board);
bool board_is_valid_move(const opera::Board& board, rust::Str move_str);
void board_reset(opera::Board& board);
bool board_is_in_check(const opera::Board& board);
bool board_is_checkmate(const opera::Board& board);
bool board_is_stalemate(const opera::Board& board);

// Search operations - real SearchEngine integration
std::unique_ptr<opera::SearchEngineWrapper> create_search_engine(opera::Board& board);
void search_engine_search(opera::SearchEngineWrapper& engine, const opera::FFISearchLimits& limits, opera::FFISearchResult& result);
void search_engine_stop(opera::SearchEngineWrapper& engine);
bool search_engine_is_searching(const opera::SearchEngineWrapper& engine);
void search_engine_reset(opera::SearchEngineWrapper& engine);

// Engine configuration
bool engine_set_hash_size(uint32_t size_mb);
bool engine_set_threads(uint32_t thread_count);
bool engine_clear_hash();

// Rust callback declarations (implemented in Rust)
void on_search_progress(const opera::FFISearchInfo& info) noexcept;
void on_engine_error(const std::string& error_msg) noexcept;